### ISSUE TITLE
Missing 'requirements.txt' file

### ISSUE THREAD

**Issue by sperciva** [tdavislab/mapper-xmean-cover#1]
There is currently an error when installing because the 'requirements.txt' file is missing:

`    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/d4/381w408j57s50y6dyx29c0hr0000gn/T/pip-req-build-vc8zoa34/setup.py", line 5, in <module>
        with open("requirements.txt", "r") as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`

I fixed this by taking the '[requirements-docs.txt](https://github.com/MapperInteractive/MapperInteractive/blob/master/requirements-docs.txt)' file from the Mapper Interactive repo, renaming it 'requirements.txt', and putting it in my directory.

**Comment by nithinvc** [comment]
I've added a requirements.txt. The previous .gitignore ignored the original requirements.txt. On my machine, the code installs normally now.
